#!/bin/sh

###
# This program is copyright Alec Muffett 1991, and is provided as part of
# the Crack v4.0 Password Cracking package.  The author disclaims all
# responsibility or liability with respect to it's usage or its effect
# upon hardware or computer systems, and maintains copyright as set out in
# the "LICENCE" document which accompanies distributions of Crack v4.0 and
# upwards. So there...
###

###
# This program provides a quick network murder if running "Crack -network"
###
# The name is Chris Samuel's fault... "Plaster the Cracks" indeed...
# Mail admiration of this joke to chris@rivers.dra.hmg.gb - april '95
###

for i in Runtime/D*
do
	echo $i
	$i
done

exit 0
